spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: agenda.exchange
    queue.post: agenda.queue.post
    queue.get: agenda.queue.get
    routingkey.post: agenda.routingkey.post
    routingkey.get: agenda.routingkey.get
server:
  port: 8082
  servlet:
    context-path: /api/v1
