spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: goose.rmq2.cloudamqp.com
    password: nc7c9ImeBgskdgB1DKTPATjekMRYm-SD
    port: 15672
    username: hktkskib
    exchange: agenda.exchange
    queue: agenda.queue
    routingkey: agenda.routingkey
server:
  port: 8082
  servlet:
    context-path: /api/v1
rabbit:
  uri: amqps://hktkskib:nc7c9ImeBgskdgB1DKTPATjekMRYm-SD@goose.rmq2.cloudamqp.com/hktkskib
