FROM adoptopenjdk/openjdk11:ubi
COPY agenda-producer-service-0.0.1-SNAPSHOT.jar agenda-producer-service-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD ["java", "-jar","agenda-producer-service-0.0.1-SNAPSHOT.jar"]
