version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  service-authentication: # <--- this is the name of the service and should be unique.
    image: service-authentication:latest # <--- this is the image of which the service will be based upon.
    hostname: service-authentication # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8081:8080 
  service-agenda: 
    image: service-agenda:latest 
    hostname: service-agenda 
    restart: always
    ports:
      - 8082:8080 
  service-alarm: 
    image: service-alarm:latest 
    hostname: service-alarm 
    restart: always 
    ports:
      - 8083:8080