server:
  jackson:
    serialization:
      fail-on-empty-beans: false
  port: 8081
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: agenda.exchange
    queue: agenda.queue
    routingkey: agenda.routingkey
