spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysqlserveremre.mysql.database.azure.com:3306/user_db?useSSL=true&requireSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: emre_db@mysqlserveremre
    password: SecurePassword123
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: goose.rmq2.cloudamqp.com
    port: 15672
    username: hktkskib
    password: nc7c9ImeBgskdgB1DKTPATjekMRYm-SD
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
server:
  port: 8081
  servlet:
    context-path: /api/v1
rabbit:
  uri: amqps://hktkskib:nc7c9ImeBgskdgB1DKTPATjekMRYm-SD@goose.rmq2.cloudamqp.com/hktkskib
jwt:
  jwtSecret: Emre_Super_Secret_Key #Mijn super veilige en geheime jwt key
  jwtExpirationMs: 900000 #jwt is 15 minuten actief
