on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: emreregistry.azurecr.io
        username: ${{ secrets.acr_emreregistry_username }}
        password: ${{ secrets.acr_emreregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/auth-producer-service" -f  "auth-producer-service/Dockerfile" -t emreregistry.azurecr.io/emrekubernetes:${{ github.sha }} --label dockerfile-path=auth-producer-service/Dockerfile
        docker push emreregistry.azurecr.io/emrekubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_emrekubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep emre-kubernetes8d74 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace emre-kubernetes8d74`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: emre-kubernetes8d74
        container-registry-url: emreregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_emreregistry_username }}
        container-registry-password: ${{ secrets.acr_emreregistry_password }}
        secret-name: emrekubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: emre-kubernetes8d74
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
          manifests/ingress-3.yml
        images: |
          emreregistry.azurecr.io/emrekubernetes:${{ github.sha }}
        imagepullsecrets: |
          emrekubernetdockerauth
