on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: emreregistry.azurecr.io
        username: ${{ secrets.acr_emreregistry_username }}
        password: ${{ secrets.acr_emreregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/auth-producer" -f  "auth-producer/Dockerfile" -t emreregistry.azurecr.io/auth-producer
        docker push emreregistry.azurecr.io/auth-producer
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_emrekubernetes_kubeConfig }}
      id: login
    
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: emreregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_emreregistry_username }}
        container-registry-password: ${{ secrets.acr_emreregistry_password }}
        secret-name: emrekubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
         {{$GITHUB_WORKSPACE}}/auth-producer-service/auth-producer-deployment.yaml
        images: |
          emreregistry.azurecr.io/auth-producer:latest
        imagepullsecrets: |
          emrekubernetdockerauth
