on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: emreregistry.azurecr.io
        username: ${{ secrets.acr_emreregistry_username }}
        password: ${{ secrets.acr_emreregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/agenda-consumer-service" -f  "agenda-consumer-service/Dockerfile" -t emreregistry.azurecr.io/emrekubernetes2:${{ github.sha }} --label dockerfile-path=agenda-consumer-service/Dockerfile
        docker push emreregistry.azurecr.io/emrekubernetes2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_emrekubernetes2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testservice | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testservice`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testservice
        container-registry-url: emreregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_emreregistry_username }}
        container-registry-password: ${{ secrets.acr_emreregistry_password }}
        secret-name: emrekubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testservice
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
          manifests/ingress-5.yml
        images: |
          emreregistry.azurecr.io/emrekubernetes2:${{ github.sha }}
        imagepullsecrets: |
          emrekubernetdockerauth
