name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build API microservices
      env: 
        PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: |
        docker-compose run -f ./deployment/docker-compose.yaml up -d
        echo $PAT | docker login ghcr.io -u emredogan -p ${{secrets.GITHUB_TOKEN}}
