name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build API microservices
      env: 
        PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: |
        echo $PAT | docker login ghcr.io -u emredogan -p ${{secrets.GITHUB_TOKEN}}
        docker build ./agenda-consumer --file ./agenda-consumer-service/Dockerfile --tag ghcr.io/microserv-indiv-backend/agenda-consumer-service:latest
        docker build ./agenda-producer --file ./agenda-producer-service/Dockerfile --tag ghcr.io/microserv-indiv-backend/agenda-producer-service:latest
        docker build ./auth-consumer --file ./auth-consumer-service/Dockerfile --tag ghcr.io/microserv-indiv-backend/auth-consumer-service:latest
        docker build ./auth-producer --file ./auth-producer-service/Dockerfile --tag ghcr.io/microserv-indiv-backend/auth-producer-service:latest
